models:
  - model: Qwen2.5-7B-lora-v1
    parameters:
      density: 1
      weight: 1
  - model: Qwen2.5-7B-lora-v2
    parameters:
      density: 1
      weight: 1
  - model: Qwen2.5-7B-lora-v3
    parameters:
      density: 1
      weight: 1
  - model: Qwen2.5-7B-lora-v4
    parameters:
      density: 1
      weight: 1
  - model: Qwen/Qwen2.5-7B-Instruct
    parameters:
      density: 1
      weight: 1
merge_method: ties
base_model: Qwen/Qwen2.5-7B
parameters:
  int8_mask: true
  nomalize: true
  weight: 1
  density: 1
tokenizer_source: Qwen/Qwen2.5-7B-Instruct
dtype: bfloat16
